version: '3'
services:
  frontend:
    image: testregistry2402.azurecr.io/my-website-frontend:latest
    networks:
      - my-app-network
    ports:
      - "8080:80"
  backend:
    image: testregistry2402.azurecr.io/my-website-backend:latest
    networks:
      - my-app-network
    ports:
      - "3000:3000"
networks:
  my-app-network:
    driver: bridge