version: '3'
services:
  frontend:
    build: ./frontend
    networks:
      - my-app-network
    ports:
      - "8080:80"
  backend:
    build: ./backend
    networks:
      - my-app-network
    ports:
      - "3000:3000"
networks:
  my-app-network:
    driver: bridge