name: Deploy Dockerized App

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t my-website-backend:latest ./backend
        docker build -t my-website-frontend:latest ./frontend

    # Stop and remove the existing container (if running)
    - name: Stop Existing Container
      run: |
        docker stop my-website-backend || true
        docker rm my-website-backend || true
        docker stop my-website-frontend || true
        docker rm my-website-frontend || true

    # Run the Docker container
    - name: Run Docker Container
      run: |
        docker run -d \
          --name my-website-backend \
          -p 3000:3000 \
          my-website-backend:latest
        
          docker run -d \
          --name my-website-frontend \
          -p 8080:80 \
          my-website-frontend:latest
