name: Deploy Dockerized App

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t my-dockerized-app:latest .

    # Stop and remove the existing container (if running)
    - name: Stop Existing Container
      run: |
        docker stop my-dockerized-app || true
        docker rm my-dockerized-app || true

    # Run the Docker container
    - name: Run Docker Container
      run: |
        docker run -d \
          --name my-dockerized-app \
          -p 8000:80 \
          my-dockerized-app:latest
