name: Build and Deploy to Azure VM
on:
  workflow_run:
    workflows: ["SonarQube Analysis"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        run: |
          az acr login --name testregistry2402

      - name: Build and Push Backend Image
        run: |
          docker build -t testregistry2402.azurecr.io/my-website-backend:latest ./backend
          docker push testregistry2402.azurecr.io/my-website-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t testregistry2402.azurecr.io/my-website-frontend:latest ./frontend
          docker push testregistry2402.azurecr.io/my-website-frontend:latest

      # Deploy to Azure VM
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          script: |
            az acr login --name testregistry2402

            docker pull testregistry2402.azurecr.io/my-website-backend:latest
            docker pull testregistry2402.azurecr.io/my-website-frontend:latest

            docker stop my-website-backend-azure-image || true && docker rm my-website-backend-azure-image || true
            # even if the commands fails || true ensures that script still runs

            docker stop my-website-frontend-azure-image || true && docker rm my-website-frontend-azure-image || true

            docker network inspect my-app-network || docker network create my-app-network

            docker run -d \
              --name my-website-backend-azure-image \
              --network my-app-network \
              -p 3000:3000 \
              testregistry2402.azurecr.io/my-website-backend:latest

            docker run -d \
              --name my-website-frontend-azure-image \
              --network my-app-network \
              -p 8080:80 \
              testregistry2402.azurecr.io/my-website-frontend:latest
