name: Deploy to Azure VM
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use GitHub-hosted runner for build
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to Azure Container Registry
      - name: Azure Container Registry Login
        run: |
          az acr login --name testregistry2402

      # Build and Push Backend Image
      - name: Build and Push Backend Image
        run: |
          docker build -t testregistry2402.azurecr.io/my-website-backend:latest ./backend
          docker push testregistry2402.azurecr.io/my-website-backend:latest

      # Build and Push Frontend Image
      - name: Build and Push Frontend Image
        run: |
          docker build -t testregistry2402.azurecr.io/my-website-frontend:latest ./frontend
          docker push testregistry2402.azurecr.io/my-website-frontend:latest

      # Deploy to Azure VM
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          script: |
            # Login to Azure Container Registry
            az acr login --name testregistry2402

            # Pull latest images
            docker pull testregistry2402.azurecr.io/my-website-backend:latest
            docker pull testregistry2402.azurecr.io/my-website-frontend:latest

            docker network inspect my-app-network >/dev/null 2>&1 || \
            docker network create my-app-network

            # Run new containers
            docker run -d \
              --name my-website-backend-azure-image \
              --network my-app-network \
              -p 3000:3000 \
              testregistry2402.azurecr.io/my-website-backend:latest

            docker run -d \
              --name my-website-frontend-azure-image \
              --network my-app-network \
              -p 8080:80 \
              testregistry2402.azurecr.io/my-website-frontend:latest

